server:
  port: 9010

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/razorpay-merchant-db

jwt:
  secret-key: asf8asfdooijfalkj123u4015jlkjf98790890890u90jvakglsdfjn8yuh

webhoook:
  secret-encryption-key: h6qLKs/lPaCBryH8Yhn2xRV21Ym0zsNMJ/KqKUDrUG8=  
